//tag::ref-doc[]
= Http Source

A source application that listens for HTTP requests and emits the body as a message payload.
If the Content-Type matches `text/*` or `application/json`, the payload will be a String,
otherwise the payload will be a byte array.

== Input

N/A 

== Output

==== Headers:

* `Content-Type: Any`

==== Payload:

If content type matches `text/*` or `application/json` 

* `String`

If content type does not match `text/*` or `application/json` 

* `byte array`

== Options

The **$$http$$** $$source$$ supports the following configuration properties:

//tag::configuration-properties[]
$$http.mapped-request-headers$$:: $$Headers that will be mapped.$$ *($$String[]$$, default: `$$<none>$$`)*
$$http.path-pattern$$:: $$An Ant-Style pattern to determine which http requests will be captured.$$ *($$String$$, default: `$$/$$`)*
$$server.port$$:: $$Server HTTP port.$$ *($$Integer$$, default: `$$<none>$$`)*
//end::configuration-properties[]

NOTE: Security is disabled for this application by default.
To enable it, you should use standard Spring Boot `security.basic.enabled = true` property.

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one one of the folders and build it:
```
$ ./mvnw clean package
```

== Examples

```
java -jar http_source.jar
```

//end::ref-doc[]
